version: '3.8'
services:
  app:
    build: .
    command: make dev
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:7
    ports:
      - "6379:6379" 