version: '3.8'
services:
  app:
    build: .
    command: make dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_RUN_PORT=8000
  redis:
    image: redis:7
    ports:
      - "6379:6379" 